# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('admin_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('admin_pw', models.CharField(max_length=32)),
                ('admin_lv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=10000)),
                ('date', models.DateTimeField()),
                ('edit_date', models.DateTimeField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commentor',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(default='static/Portfolio/img/comment/commentor/default.png', max_length=30)),
                ('picture', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail_pic', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('context', models.CharField(blank=True, max_length=10000, null=True)),
                ('type', models.SmallIntegerField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Content')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAccessToken',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('refresh_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_code', models.IntegerField(primary_key=True, serialize=False)),
                ('menu_title', models.CharField(max_length=20)),
                ('submenu_title', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='menu',
            field=models.ForeignKey(db_column='menu_code', on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Menu'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentor',
            field=models.ForeignKey(db_column='commentor_email', on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Commentor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Content'),
        ),
    ]
