# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_admininfo_fails'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='fail_time',
            field=models.DateTimeField(default='2000-01-01 00:00:00.000'),
        ),
    ]
